# Generated by Django 3.2.6 on 2021-08-08 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sub_header',
            new_name='Article_Title',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='header',
            new_name='Content_Type',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='character_len',
            new_name='Words_Per_Column',
        ),
    ]
