# Generated by Django 3.2.6 on 2021-08-08 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_auto_20210808_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Content_Type',
            new_name='Article_Url',
        ),
    ]
